version: '3.8'

services:
  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=conscience
      - POSTGRES_USER=god
      - POSTGRES_PASSWORD=password

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=conscience
      - POSTGRES_USER=god
      - POSTGRES_PASSWORD=password