version: '3.8'

services:
  db:
    ports:
      - "5432:5432"
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=conscience
      - POSTGRES_USER=god
      - POSTGRES_PASSWORD=password

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=conscience
      - POSTGRES_USER=god
      - POSTGRES_PASSWORD=password

  pgadmin:
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - /var/lib/pgadmin